services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      - CORS_ALLOW_ORIGINS=http://localhost:4173,http://127.0.0.1:4173,http://frontend:4173
    volumes:
      - ./backend/app:/app/app
    ports:
      - "8000:8000"
    networks:
      - molecule-stack

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        VITE_API_BASE_URL: http://localhost:8000
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
    depends_on:
      - backend
    ports:
      - "4173:4173"
    networks:
      - molecule-stack
    volumes:
      - node-modules-cache:/root/.npm

networks:
  molecule-stack:
    driver: bridge

volumes:
  node-modules-cache:
